import {init,$,fmt,bind} from '../assets/lab-ui.mjs';
import {seeded,pagerank,betweenness,sum} from '../assets/lab-math.mjs';
import {LAB_I} from '../assets/lab-i18n.mjs';
const lab=init(LAB_I['05'],'05');let seed=2026,selected=0;
function generate(n,p){const rng=seeded(seed),edges=[];for(let s=0;s<n;s++)for(let t=0;t<n;t++)if(s!==t&&rng()<p)edges.push({s,t,w:1+Math.floor(rng()*9)});return edges;}
function render(){
 const n=+$('#nodes').value,p=+$('#density').value,weighted=$('#weighted').checked,edges=generate(n,p);selected=Math.min(selected,n-1);
 $('#nv').textContent=n;$('#dv').textContent=fmt(p,2);$('#selected').innerHTML=Array.from({length:n},(_,i)=>'<option value="'+i+'">A'+(i+1)+'</option>').join('');$('#selected').value=selected;
 const pr=pagerank(n,edges,weighted),bt=betweenness(n,edges),rows=Array.from({length:n},(_,i)=>({node:i,inDegree:edges.filter(e=>e.t===i).length,outDegree:edges.filter(e=>e.s===i).length,inStrength:sum(edges.filter(e=>e.t===i).map(e=>e.w)),outStrength:sum(edges.filter(e=>e.s===i).map(e=>e.w)),pageRank:pr[i],betweenness:bt[i]})),st=rows[selected];
 $('#inD').textContent=st.inDegree;$('#outD').textContent=st.outDegree;$('#pr').textContent=fmt(st.pageRank,4);$('#bt').textContent=fmt(st.betweenness,4);
 const actual=edges.length/(n*(n-1));$('#insight').textContent=lab.t('A'+(selected+1)+' · '+edges.length+' aristas · densidad observada '+fmt(actual,3)+'. Fuerza entrante/saliente: '+st.inStrength+'/'+st.outStrength+' transacciones agregadas. PageRank '+(weighted?'ponderado':'no ponderado')+'; betweenness dirigida no ponderada y normalizada. Semilla '+seed+'.','A'+(selected+1)+' · '+edges.length+' edges · observed density '+fmt(actual,3)+'. In/out strength: '+st.inStrength+'/'+st.outStrength+' aggregated transactions. '+(weighted?'Weighted':'Unweighted')+' PageRank; normalized directed unweighted betweenness. Seed '+seed+'.');
 const pos=rows.map((_,i)=>{const a=2*Math.PI*i/n-Math.PI/2;return[450+330*Math.cos(a),255+180*Math.sin(a)];});let svg='<defs><marker id="arrow" viewBox="0 0 10 10" refX="9" refY="5" markerWidth="5" markerHeight="5" orient="auto"><path d="M0 0L10 5L0 10z" fill="var(--muted)"/></marker><marker id="activeArrow" viewBox="0 0 10 10" refX="9" refY="5" markerWidth="5" markerHeight="5" orient="auto"><path d="M0 0L10 5L0 10z" fill="var(--accent2)"/></marker></defs>';
 edges.forEach(e=>{const [x1,y1]=pos[e.s],[x2,y2]=pos[e.t],dx=x2-x1,dy=y2-y1,l=Math.hypot(dx,dy),ux=dx/l,uy=dy/l,cx=(x1+x2)/2-uy*18,cy=(y1+y2)/2+ux*18,active=e.s===selected||e.t===selected;
  svg+='<path d="M'+(x1+ux*29)+','+(y1+uy*29)+' Q'+cx+','+cy+' '+(x2-ux*34)+','+(y2-uy*34)+'" fill="none" stroke="'+(active?'var(--accent2)':'var(--muted)')+'" stroke-opacity="'+(active?.9:.16)+'" stroke-width="'+(active?2+e.w/4:1.2)+'" marker-end="url(#'+(active?'activeArrow':'arrow')+')"/>';if(active)svg+='<text x="'+cx+'" y="'+(cy-8)+'" text-anchor="middle" fill="var(--text)" font-size="17">'+e.w+'</text>';
 });
 rows.forEach((r,i)=>{const[x,y]=pos[i],active=i===selected;svg+='<g class="node" data-node="'+i+'" tabindex="0" role="button" aria-label="'+lab.t('Seleccionar dirección ','Select address ')+'A'+(i+1)+'"><circle cx="'+x+'" cy="'+y+'" r="'+(active?30:25)+'" fill="'+(active?'var(--accent)':'var(--panel2)')+'" stroke="'+(active?'var(--accent)':'var(--border)')+'" stroke-width="3"/><text x="'+x+'" y="'+(y+6)+'" text-anchor="middle" fill="'+(active?'var(--bg)':'var(--text)')+'" font-size="18" font-weight="800">A'+(i+1)+'</text></g>';});$('#graphSvg').innerHTML=svg;
 document.querySelectorAll('[data-node]').forEach(el=>{const pick=()=>{selected=+el.dataset.node;render();};el.addEventListener('click',pick);el.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();pick();$('#selected').focus();}});});
 $('#tbody').innerHTML=[...rows].sort((a,b)=>b.pageRank-a.pageRank).map(r=>'<tr><td><button data-pick="'+r.node+'">A'+(r.node+1)+'</button></td><td>'+r.inDegree+'</td><td>'+r.outDegree+'</td><td>'+r.inStrength+'</td><td>'+r.outStrength+'</td><td>'+fmt(r.pageRank,4)+'</td><td>'+fmt(r.betweenness,4)+'</td></tr>').join('');document.querySelectorAll('[data-pick]').forEach(b=>b.addEventListener('click',()=>{selected=+b.dataset.pick;render();}));
 $('#edgeTable').innerHTML=edges.filter(e=>e.s===selected||e.t===selected).map(e=>'<tr><td>A'+(e.s+1)+'</td><td>→ A'+(e.t+1)+'</td><td>'+e.w+'</td></tr>').join('')||'<tr><td colspan="3">'+lab.t('Dirección aislada','Isolated address')+'</td></tr>';
 lab.commit({kind:'synthetic-directed-address-graph',seed,config:{nodes:n,edgeProbability:p,weightedPageRank:weighted,selected},results:{observedDensity:actual,edges,rows,pageRankSum:sum(pr)}});
}
bind(['nodes','density'],'input',render);bind(['weighted'],'change',render);$('#selected').addEventListener('change',()=>{selected=+$('#selected').value;render();});$('#regen').addEventListener('click',()=>{seed++;render();});$('#reset').addEventListener('click',()=>{seed=2026;selected=0;$('#nodes').value=10;$('#density').value=.24;$('#weighted').checked=false;render();});lab.onUpdate(render);render();
