import {init,$,fmt,bind,coefficientRows} from '../assets/lab-ui.mjs';
import {gnnStates,adjacency,sum,W,WS} from '../assets/lab-math.mjs';
import {LAB_I} from '../assets/lab-i18n.mjs';
const lab=init(LAB_I['06'],'06'),names=['A','B','C','D','E','F'],H0=[[.9,.2],[.2,.8],[.7,.6],[.15,.25],[.55,.15],[.35,.7]],edges=[[0,1],[0,2],[1,2],[1,3],[2,4],[2,5],[3,5],[4,5]],pos=[[135,230],[320,100],[455,285],[625,100],[750,345],[745,210]],adj=adjacency(6,edges);
$('#node').innerHTML=names.map((n,i)=>'<option value="'+i+'">'+n+'</option>').join('');
function render(){
 const arch=$('#arch').value,target=+$('#node').value,L=+$('#layer').value,{states,traces}=gnnStates(H0,edges,arch,L),H=states.at(-1),trace=L?traces.at(-1)[target]:null;$('#lv').textContent=L;$('#step').disabled=L===6;$('#emb').textContent='h'+names[target]+'⁽'+L+'⁾ = ['+H[target].map(v=>fmt(v)).join(', ')+']';
 let reached=new Set([target]);for(let k=0;k<L;k++){const next=new Set(reached);for(const v of reached)for(const u of adj[v])next.add(u);reached=next;}
 let svg='';edges.forEach(([a,b])=>{const active=L>0&&(a===target||b===target);svg+='<line x1="'+pos[a][0]+'" y1="'+pos[a][1]+'" x2="'+pos[b][0]+'" y2="'+pos[b][1]+'" stroke="'+(active?'var(--accent2)':'var(--muted)')+'" stroke-opacity="'+(active?.9:.25)+'" stroke-width="'+(active?4:2)+'"'+(active?' class="message-flow"':'')+'/>';});
 names.forEach((name,i)=>{const[x,y]=pos[i],sel=i===target;svg+='<g class="node" data-node="'+i+'" tabindex="0" role="button" aria-label="'+lab.t('Seleccionar nodo ','Select node ')+name+'"><circle cx="'+x+'" cy="'+y+'" r="'+(sel?32:27)+'" fill="'+(sel?'var(--accent)':'var(--panel2)')+'" stroke="'+(reached.has(i)?'var(--accent2)':'var(--border)')+'" stroke-width="3"/><text x="'+x+'" y="'+(y+6)+'" text-anchor="middle" fill="'+(sel?'var(--bg)':'var(--text)')+'" font-size="20" font-weight="800">'+name+'</text><text x="'+x+'" y="'+(y+56)+'" text-anchor="middle" fill="var(--muted)" font-size="17">['+H[i].map(v=>fmt(v,2)).join(', ')+']</text></g>';});$('#svg').innerHTML=svg;
 document.querySelectorAll('[data-node]').forEach(el=>{const pick=()=>{$('#node').value=el.dataset.node;render();};el.addEventListener('click',pick);el.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();pick();$('#node').focus();}});});
 $('#weights').innerHTML=trace?coefficientRows(trace.ids.map((id,i)=>({name:names[id]+(id===target?lab.t(' · propio',' · self'):''),weight:trace.weights[i]}))):'<p class="muted">'+lab.t('Capa 0: sin agregación todavía.','Layer 0: no aggregation yet.')+'</p>';
 let explanation=lab.t('Features iniciales; no se aplicó una capa.','Initial features; no layer applied.');if(trace){const total=sum(trace.weights);explanation=arch==='GCN'?lab.t('GCN simétrica: incluye self-loop. La suma de coeficientes '+fmt(total)+' no tiene que ser 1.','Symmetric GCN: includes a self-loop. The coefficient sum '+fmt(total)+' need not equal 1.'):arch==='GraphSAGE'?lab.t('GraphSAGE: estado propio concatenado con media de vecinos; la media suma '+fmt(total)+'.','GraphSAGE: self state concatenated with neighbor mean; mean weights sum to '+fmt(total)+'.'):lab.t('GAT: una cabeza, self-loop y softmax. Σα = '+fmt(total)+'.','GAT: one head, self-loop and softmax. Σα = '+fmt(total)+'.');}
 $('#msg').textContent=explanation+' '+lab.t('Campo receptivo: ','Receptive field: ')+[...reached].map(i=>names[i]).sort().join(', ')+'.';
 $('#trace').textContent=trace?lab.t('Agregado','Aggregate')+': ['+trace.aggregate.map(v=>fmt(v,6)).join(', ')+']\n'+lab.t('Salida ReLU','ReLU output')+': ['+trace.output.map(v=>fmt(v,6)).join(', ')+']':lab.t('Sin transformación en capa 0.','No transformation at layer 0.');
 $('#matrix').textContent=(arch==='GraphSAGE'?'W_S = '+JSON.stringify(WS):'W = '+JSON.stringify(W))+(arch==='GAT'?'\na = [0.6, −0.4, 0.8, 0.3]; LeakyReLU slope = 0.2':'');
 lab.commit({kind:'fixed-weight-gnn-exact-message-passing',config:{architecture:arch,target,layer:L},results:{initialFeatures:H0,edges,embeddings:H,trace,receptiveField:[...reached],weights:arch==='GraphSAGE'?WS:W}});
}
bind(['arch','node'],'change',render);bind(['layer'],'input',render);$('#step').addEventListener('click',()=>{$('#layer').value=Math.min(6,+$('#layer').value+1);render();});$('#reset').addEventListener('click',()=>{$('#arch').value='GCN';$('#node').value=0;$('#layer').value=1;render();});lab.onUpdate(render);render();
