import {init,$,fmt,bind,lineChart} from '../assets/lab-ui.mjs';
import {gnnLayer,mean,recurrentStep} from '../assets/lab-math.mjs';
import {LAB_I} from '../assets/lab-i18n.mjs';
const lab=init(LAB_I['07'],'07'),H0=[[.8,.2],[.2,.7],[.6,.5],[.1,.3],[.5,.2]],edgeSets=[[[0,1],[1,2],[2,3]],[[0,1],[1,2],[2,3],[2,4]],[[0,1],[0,2],[1,2],[2,4],[3,4]],[[0,2],[1,2],[1,3],[2,4],[3,4],[0,4]],[[0,1],[0,2],[1,3],[2,3],[2,4],[3,4],[1,4]]],pos=[[125,205],[300,95],[450,255],[625,95],[770,230]];let t=0,timer=null;
function sequence(gnn,rnn){let h=0,c=0;const states=[];for(let k=0;k<=t;k++){const initial=H0.map((v,i)=>[v[0]+.03*k*(i%2?1:-1),v[1]+.02*k*(i%3-1)]),H=gnnLayer(initial,edgeSets[k],gnn).output,z=[mean(H.map(v=>v[0])),mean(H.map(v=>v[1])),edgeSets[k].length/10],x=.85*z[0]+.55*z[1]+.35*z[2],st=recurrentStep(x,h,c,rnn);states.push({t:k+1,initial,H,graphEmbedding:z,x,hPrevious:h,cPrevious:c,...st});h=st.h;c=st.c??0;}return states;}
function stop(){clearInterval(timer);timer=null;$('#play').textContent=lab.t('Reproducir','Play');}
function render(){
 const gnn=$('#gnnArch').value,rnn=$('#rnnArch').value,states=sequence(gnn,rnn),st=states.at(-1),edges=edgeSets[t];$('#prev').disabled=t===0;$('#next').disabled=t===4;$('#timePill').textContent='t = '+(t+1)+' / 5';$('#z').textContent='['+st.graphEmbedding.map(v=>fmt(v)).join(', ')+']';$('#hh').textContent=fmt(st.h,6);$('#pred').textContent=fmt(st.p,6);
 // z denotes graph embedding in the display. The GRU update gate is stored separately.
 const gate=recurrentStep(st.x,st.hPrevious,st.cPrevious,rnn);$('#ig').textContent=fmt(rnn==='LSTM'?gate.i:gate.z,6);$('#fg').textContent=fmt(rnn==='LSTM'?gate.f:gate.r,6);$('#gate1Label').textContent=rnn==='LSTM'?'iₜ · '+lab.t('entrada','input'):'zₜ · '+lab.t('actualización','update');$('#gate2Label').textContent=rnn==='LSTM'?'fₜ · '+lab.t('olvido','forget'):'rₜ · reset';
 const vector=st.graphEmbedding||st.z;$('#z').textContent='['+vector.map(v=>fmt(v)).join(', ')+']';
 let svg='';edges.forEach(([a,b])=>svg+='<line x1="'+pos[a][0]+'" y1="'+pos[a][1]+'" x2="'+pos[b][0]+'" y2="'+pos[b][1]+'" stroke="var(--accent2)" stroke-width="3"/>');H0.forEach((_,i)=>{const[x,y]=pos[i];svg+='<circle cx="'+x+'" cy="'+y+'" r="30" fill="var(--panel2)" stroke="var(--accent)" stroke-width="3"/><text x="'+x+'" y="'+(y+6)+'" text-anchor="middle" fill="var(--text)" font-size="20">'+String.fromCharCode(65+i)+'</text><text x="'+x+'" y="'+(y+55)+'" text-anchor="middle" fill="var(--muted)" font-size="17">['+st.H[i].map(v=>fmt(v,2)).join(', ')+']</text>';});$('#graph').innerHTML=svg;
 $('#graphMsg').textContent=lab.t('G'+(t+1)+': '+edges.length+' aristas. Pooling = media de 5 embeddings; se concatena densidad = aristas/10. Entrada escalar xₜ = '+fmt(st.x,6)+'. Sólo se procesa el prefijo observado.','G'+(t+1)+': '+edges.length+' edges. Pooling = mean of 5 embeddings; concatenate density = edges/10. Scalar input xₜ = '+fmt(st.x,6)+'. Only the observed prefix is processed.');
 const w=900,h=300,p=55,x=i=>p+i*(w-2*p)/4,y=v=>h-p-(h-2*p)*v;let seq='';for(let j=0;j<=4;j++){seq+='<line x1="'+p+'" y1="'+y(j/4)+'" x2="'+(w-p)+'" y2="'+y(j/4)+'" stroke="var(--grid)"/><text x="'+(p-12)+'" y="'+(y(j/4)+6)+'" text-anchor="end" fill="var(--muted)" font-size="17">'+fmt(j/4,2)+'</text>';}
 for(let i=0;i<5;i++){const s=states[i];seq+='<text x="'+x(i)+'" y="'+(h-p+28)+'" text-anchor="middle" fill="var(--muted)" font-size="18">G'+(i+1)+'</text>';if(s){if(i)seq+='<line x1="'+x(i-1)+'" y1="'+y(states[i-1].p)+'" x2="'+x(i)+'" y2="'+y(s.p)+'" stroke="var(--accent2)" stroke-width="3"/>';seq+='<circle cx="'+x(i)+'" cy="'+y(s.p)+'" r="8" fill="var(--accent)"/><text x="'+x(i)+'" y="'+(y(s.p)-16)+'" text-anchor="middle" fill="var(--text)" font-size="18">'+fmt(s.p,3)+'</text>';}else seq+='<text x="'+x(i)+'" y="150" text-anchor="middle" fill="var(--muted)" font-size="17">'+lab.t('pendiente','pending')+'</text>';}
 $('#seq').innerHTML=seq;$('#pipelineFormula').textContent='Gₜ → '+gnn+' → mean(Hₜ) || density → xₜ → '+rnn+' → hₜ → σ(2.2hₜ − 0.25)';
 const details=rnn==='LSTM'?'i = '+fmt(gate.i,6)+' · f = '+fmt(gate.f,6)+' · o = '+fmt(gate.o,6)+' · g = '+fmt(gate.g,6)+'\ncₜ = f·cₜ₋₁ + i·g = '+fmt(gate.c,6)+'\nhₜ = o·tanh(cₜ) = '+fmt(gate.h,6):'z = '+fmt(gate.z,6)+' · r = '+fmt(gate.r,6)+' · g = '+fmt(gate.g,6)+'\nhₜ = (1−z)·g + z·hₜ₋₁ = '+fmt(gate.h,6);
 $('#gateTrace').textContent='hₜ₋₁ = '+fmt(st.hPrevious,6)+(rnn==='LSTM'?' · cₜ₋₁ = '+fmt(st.cPrevious,6):'')+'\n'+details;
 $('#stateTable').innerHTML=states.map(s=>'<tr><td>G'+s.t+'</td><td>'+s.graphEmbedding.map(v=>fmt(v,3)).join(', ')+'</td><td>'+fmt(s.x,6)+'</td><td>'+fmt(s.h,6)+'</td><td>'+fmt(s.c,6)+'</td><td>'+fmt(s.p,6)+'</td></tr>').join('');
 lab.commit({kind:'fixed-weight-causal-graph-recurrent-pipeline',config:{gnn,rnn,observedSnapshots:t+1},results:{states,scoreUnit:'dimensionless-not-calibrated-probability'}});
}
bind(['gnnArch','rnnArch'],'change',()=>{stop();render();});$('#prev').addEventListener('click',()=>{stop();t=Math.max(0,t-1);render();});$('#next').addEventListener('click',()=>{stop();t=Math.min(4,t+1);render();});$('#play').addEventListener('click',()=>{if(timer){stop();return;}if(t===4)t=0;render();$('#play').textContent=lab.t('Pausar','Pause');timer=setInterval(()=>{t++;render();if(t===4)stop();},1200);});$('#reset').addEventListener('click',()=>{stop();t=0;$('#gnnArch').value='GCN';$('#rnnArch').value='LSTM';render();});lab.onUpdate(()=>{stop();render();});render();
