import {init,$,fmt,esc} from '../assets/lab-ui.mjs';
import {linearExplanation,sum} from '../assets/lab-math.mjs';
import {LAB_I} from '../assets/lab-i18n.mjs';
const lab=init(LAB_I['08'],'08'),cfg={BTC:{names:[['Volatilidad','Volatility'],['Volumen','Volume'],['Direcciones activas','Active addresses'],['Comisiones','Fees'],['RSI','RSI']],w:[-.75,.42,.55,.30,-.18],x:[.72,.66,.58,.62,.44]},ETH:{names:[['Gas','Gas'],['Direcciones activas','Active addresses'],['Quema','Burn'],['TVL','TVL'],['Volumen DEX','DEX volume']],w:[-.34,.62,.48,.40,.36],x:[.64,.70,.57,.61,.68]}};let values={BTC:cfg.BTC.x.slice(),ETH:cfg.ETH.x.slice()};
function build(){const a=$('#asset').value,c=cfg[a];$('#sliders').innerHTML=c.names.map((name,i)=>'<div class="control"><label for="feature'+i+'"><span>'+lab.t(...name)+'</span><strong id="v'+i+'">'+fmt(values[a][i],2)+'</strong></label><input id="feature'+i+'" data-feature="'+i+'" type="range" min="0" max="1" step="0.01" value="'+values[a][i]+'"></div>').join('');document.querySelectorAll('[data-feature]').forEach(el=>el.addEventListener('input',()=>{values[a][+el.dataset.feature]=+el.value;render();}));render();}
function render(){
 const asset=$('#asset').value,c=cfg[asset],mu=Array(5).fill(+$('#reference').value),intercept=.02-.5*sum(c.w),{base,phi,output,residual}=linearExplanation(c.w,values[asset],mu,intercept);$('#refV').textContent=fmt(mu[0],2);values[asset].forEach((v,i)=>$('#v'+i).textContent=fmt(v,2));$('#base').textContent=fmt(base,4);$('#sum').textContent=fmt(sum(phi),4);$('#out').textContent=fmt(output,4);$('#check').textContent=Math.abs(residual)<1e-10?'✓ < 10⁻¹⁰':'✗';
 const w=900,h=420,left=280,right=70,center=(left+w-right)/2,half=(w-right-left)/2,max=Math.max(.08,...phi.map(Math.abs))*1.25,scale=half/max;let svg='<line x1="'+center+'" y1="40" x2="'+center+'" y2="385" stroke="var(--muted)" stroke-width="2"/>';
 for(let j=-2;j<=2;j++){const v=max*j/2,x=center+v*scale;svg+='<text x="'+x+'" y="32" text-anchor="middle" fill="var(--muted)" font-size="17">'+fmt(v,2)+'</text>';}
 phi.forEach((p,i)=>{const y=80+i*63,len=Math.abs(p)*scale,x=p>=0?center:center-len;svg+='<text x="24" y="'+(y+7)+'" fill="var(--text)" font-size="18">'+esc(lab.t(...c.names[i]))+'</text><rect x="'+x+'" y="'+(y-17)+'" width="'+Math.max(.8,len)+'" height="34" rx="5" fill="'+(p>=0?'var(--accent)':'var(--danger)')+'"/><text x="'+(p>=0?x+len+9:x-9)+'" y="'+(y+6)+'" text-anchor="'+(p>=0?'start':'end')+'" fill="var(--text)" font-size="17">'+(p>=0?'+':'')+fmt(p,3)+'</text>';});$('#chart').innerHTML=svg;
 $('#equation').textContent='f(x) = '+fmt(base,4)+' + ('+fmt(sum(phi),4)+') = '+fmt(output,4)+' · '+lab.t('residuo numérico ','numerical residual ')+residual.toExponential(2);
 $('#explainTable').innerHTML=c.names.map((name,i)=>'<tr><td>'+esc(lab.t(...name))+'</td><td>'+fmt(values[asset][i],2)+'</td><td>'+fmt(mu[i],2)+'</td><td>'+fmt(c.w[i],2)+'</td><td>'+fmt(phi[i],4)+'</td></tr>').join('');
 const accum=[base];phi.forEach(p=>accum.push(accum.at(-1)+p));const lo=Math.min(0,...accum),hi=Math.max(0,...accum),margin=(hi-lo)*.15+.02,pad=65,sy=v=>300-pad-(300-2*pad)*(v-lo+margin)/(hi-lo+2*margin),sx=i=>pad+i*(w-2*pad)/6;let water='<line x1="'+pad+'" y1="'+sy(0)+'" x2="'+(w-pad)+'" y2="'+sy(0)+'" stroke="var(--grid)"/>';
 const bars=[{start:0,end:base,label:lab.t('Base','Base')},...phi.map((p,i)=>({start:accum[i],end:accum[i+1],label:String(i+1)})),{start:0,end:output,label:lab.t('Salida','Output')}];bars.forEach((b,i)=>{const x=sx(i),y=Math.min(sy(b.start),sy(b.end)),height=Math.max(1,Math.abs(sy(b.start)-sy(b.end)));water+='<rect x="'+(x-30)+'" y="'+y+'" width="60" height="'+height+'" rx="4" fill="'+(i===0||i===6?'var(--accent2)':b.end>=b.start?'var(--accent)':'var(--danger)')+'"/><text x="'+x+'" y="'+(y-10)+'" text-anchor="middle" fill="var(--text)" font-size="17">'+fmt(b.end,3)+'</text><text x="'+x+'" y="280" text-anchor="middle" fill="var(--muted)" font-size="17">'+b.label+'</text>';if(i<6)water+='<line x1="'+(x+30)+'" y1="'+sy(b.end)+'" x2="'+(sx(i+1)-30)+'" y2="'+sy(b.end)+'" stroke="var(--muted)" stroke-dasharray="4 4"/>';});$('#waterfall').innerHTML=water;
 $('#modelFormula').textContent='f(x) = b + Σwᵢxᵢ; b = '+fmt(intercept,4)+'\nφᵢ = wᵢ(xᵢ − μᵢ); E[f(X)] = b + Σwᵢμᵢ\n'+lab.t('Juego interventional con marginales independientes. Cambiar μ cambia la explicación; f(x) permanece fijo.','Interventional game with independent marginals. Changing μ changes the explanation; f(x) stays fixed.');
 lab.commit({kind:'exact-linear-interventional-shap-independent-marginals',config:{asset,values:values[asset],referenceMeans:mu,weights:c.w,intercept},results:{baseline:base,contributions:phi,output,residual,outputUnit:'dimensionless'}});
}
$('#asset').addEventListener('change',build);$('#reference').addEventListener('input',render);$('#neutral').addEventListener('click',()=>{values[$('#asset').value]=Array(5).fill(+$('#reference').value);build();});$('#reset').addEventListener('click',()=>{values={BTC:cfg.BTC.x.slice(),ETH:cfg.ETH.x.slice()};$('#asset').value='BTC';$('#reference').value=.5;build();});lab.onUpdate(build);build();
