from pathlib import Path
import json,html,math
from reportlab.platypus import SimpleDocTemplate,Paragraph,Spacer,PageBreak,Table,TableStyle,KeepTogether
from reportlab.lib.styles import ParagraphStyle
from reportlab.lib import colors
from reportlab.lib.enums import TA_LEFT
from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.ttfonts import TTFont
from reportlab.lib.pagesizes import A4

ROOT=Path(__file__).resolve().parents[1]/'unidades/u08-redes-neuronales-lstm-gnn-blockchain';data=json.loads((ROOT/'recursos/guia-contenido.json').read_text());labs=data['labs'];BASE=data['publicationBase'];AUTHOR=data['author'];PDF='Guia_U8_Simuladores_Sergio_Gevatschnaider.pdf';esc=html.escape
nav='<nav class="lab-nav"><a href="../index.html">Unidad 8</a><a href="../simuladores/index.html">Laboratorios</a><a href="../materiales/">Presentaciones</a><a href="'+PDF+'" download>Descargar PDF</a></nav>'
intro='<p>Esta guía acompaña ocho laboratorios de redes neuronales y análisis de blockchain. Cada experimento combina una pregunta, controles, resultados calculados y una interpretación. Conviene comenzar con las presentaciones de metodología y redes neuronales, y recorrer las actividades en orden.</p><div class="callout warn">BTC y ETH identifican escenarios sintéticos. La arena compara perfiles de pronóstico prefijados; no entrena los algoritmos nombrados. Las GNN y celdas recurrentes usan pesos fijos. Sólo el laboratorio 02 ajusta una regresión ridge. Los resultados enseñan mecanismos y no constituyen evidencia de desempeño en mercados reales.</div>'
common=[('EN / ES','Actualiza textos de interfaz y explicaciones; conserva el experimento.'),('Modo claro / oscuro','Cambia contraste y colores; conserva configuración y resultados.'),('Reiniciar','Restaura valores y semilla propios del laboratorio. Idioma y tema se conservan.'),('Pantalla completa','Amplía la interfaz. Esc permite salir; si el navegador lo restringe, usar F11.'),('Exportar registro','Descarga JSON con autoría, configuración, supuestos y resultados numéricos.'),('Descargar gráfico SVG','Exporta la primera visualización como gráfico vectorial.'),('Marcar actividad realizada','Guarda avance local en este navegador. No evalúa respuestas ni registra una calificación.')]
method=['Anticipá el resultado antes de cambiar un control.','Modificá una variable por vez y anotá lo que mantenés fijo.','Exportá los dos registros cuando compares configuraciones.','Distinguí cálculo exacto, dato sintético, entrenamiento y evidencia empírica.','Cerrá con una conclusión y una limitación que el experimento no pueda resolver.']
def html_table(headers,rows):return '<div class="tablewrap"><table class="table guide-table"><thead><tr>'+''.join('<th>'+esc(h)+'</th>' for h in headers)+'</tr></thead><tbody>'+''.join('<tr>'+''.join('<td>'+esc(str(v))+'</td>' for v in row)+'</tr>' for row in rows)+'</tbody></table></div>'
toc='<aside class="guide-toc"><strong>Contenido</strong><a href="#inicio">Cómo trabajar</a>'+''.join('<a href="#lab'+lab['id']+'">'+lab['id']+' · '+esc(lab['title'])+'</a>' for lab in labs)+'<a href="#vocabulario">Vocabulario general</a><a href="#docente">Cierre y evaluación</a><a href="#fuentes">Fuentes</a></aside>'
sections='<section id="inicio" class="panel"><p class="lab-kicker">Lectura crítica del experimento</p><h2>Cómo trabajar con los laboratorios</h2>'+intro+'<h3>Controles comunes</h3>'+html_table(['Control','Comportamiento'],common)+'<h3>Una rutina de investigación</h3><ol>'+''.join('<li>'+esc(s)+'</li>' for s in method)+'</ol><h3>Registro mínimo</h3>'+html_table(['Campo','Qué anotar'],[('Pregunta','Qué relación se quiere explorar.'),('Configuración','Laboratorio, semilla, activo, horizonte y controles.'),('Resultado','Métrica o traza y unidades; adjuntar JSON.'),('Interpretación','Qué cambió y qué no cambió.'),('Límite','Qué requiere datos reales, ajuste o validación adicional.')])+'</section>'
for lab in labs:
 sections+='<section id="lab'+lab['id']+'" class="panel"><p class="lab-kicker">Laboratorio '+lab['id']+' · '+str(lab['minutes'])+' minutos</p><h2>'+esc(lab['title'])+'</h2><p>'+esc(lab['description'])+'</p><div class="lab-type">'+esc(lab['type'])+'</div><p><a class="btn primary" href="../simuladores/'+lab['file']+'">Abrir experimento →</a></p><h3>Controles y consecuencias</h3>'+html_table(['Control','Valores','Qué modifica'],lab['controls'])+'<h3>Procedimiento</h3><ol>'+''.join('<li>'+esc(step)+'</li>' for step in lab['steps'])+'</ol><h3>Ejemplo comprobable</h3><div class="callout">'+esc(lab['example'])+'</div><h3>Preguntas y orientación</h3>'
 for activity in lab['activities']:sections+='<p><strong>'+esc(activity['prompt'])+'</strong></p><details><summary>Ver orientación de respuesta</summary><p>'+esc(activity['guidance'])+'</p></details>'
 sections+='<h3>Vocabulario del laboratorio</h3>'+''.join('<details><summary>'+esc(v['term'])+'</summary><p>'+esc(v['definition'])+'</p></details>' for v in lab['vocabulary'])+'</section>'
sections+='<section class="panel" id="vocabulario"><p class="lab-kicker">Consulta transversal</p><h2>Vocabulario general</h2><p>Se conservan y desarrollan los términos del apéndice de la guía docente original. Las definiciones de cada laboratorio agregan el contexto de uso y sus límites.</p>'+''.join('<details><summary>'+esc(v['term'])+'</summary><p>'+esc(v['definition'])+'</p></details>' for v in data['generalVocabulary'])+'</section>'
closing=[('Preparación y causalidad','Reconoce forma de X, fecha de etiqueta, purga y disponibilidad.'),('Cálculo y unidades','Reconstruye una métrica o una traza y conserva sus unidades.'),('Comparación controlada','Mantiene configuraciones comunes y diferencia costo de error predictivo.'),('Interpretación crítica','Distingue arquitectura, entrenamiento, atribución y causalidad.'),('Reproducibilidad','Entrega dos registros, una tabla de comparación y una conclusión con límites.')]
sections+='<section class="panel" id="docente"><h2>Cierre y evaluación docente</h2><p>Pedí una comparación con dos configuraciones del mismo laboratorio, una hipótesis previa y una explicación posterior. La marca de actividad sólo registra avance; la evidencia de aprendizaje está en el razonamiento y en la reconstrucción del cálculo.</p>'+html_table(['Criterio','Evidencia observable'],closing)+'<h3>Transferencia al proyecto real</h3><p>Documentar datos de Bitcoin o Ethereum, disponibilidad, unidad de análisis y etiquetas; ajustar baselines y modelos en train; aplicar validación temporal y evaluar la mejora incremental con ablaciones. La arena sintética y los pesos fijos sirven para preparar estas decisiones, no para sustituir ese experimento.</p></section>'
refs={r['url']:r['title'] for lab in labs for r in lab['references']}
sections+='<section class="panel" id="fuentes"><h2>Fuentes y trazabilidad</h2><p>Versión revisada del 2 de octubre de 2026, basada en los ocho HTML y la guía docente suministrados. Se revisaron fórmulas, unidades y comportamientos, y se desarrollaron los términos originales.</p><ul>'+''.join('<li><a href="'+url+'" target="_blank" rel="noopener noreferrer">'+esc(title)+'</a></li>' for url,title in refs.items())+'</ul></section>'
page='<!doctype html><html lang="es" data-theme="dark"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Guía completa · Laboratorios U8</title><link rel="stylesheet" href="../assets/lab.css"></head><body><a class="skip" href="#inicio">Saltar a la guía</a><main class="shell">'+nav+'<header class="topbar"><div class="brand"><div class="badge">U8</div><div><h1>Guía de laboratorios</h1><p>Redes neuronales, LSTM / GRU, GNN y explicabilidad</p></div></div><div class="actions"><button class="btn" data-action="theme">Modo claro</button><a class="btn primary" href="'+PDF+'" download>Descargar PDF</a></div></header><div class="guide-layout">'+toc+'<article class="guide-article">'+sections+'</article></div><footer class="footer"><strong>'+AUTHOR+'</strong><span>Versión revisada · 2 oct 2026</span></footer></main><script type="module">import {init} from "../assets/lab-ui.mjs";init({es:{},en:{}},"guide");document.documentElement.lang="es";</script></body></html>'
(ROOT/'recursos/guia-simuladores.html').write_text(page)

# A4 PDF: selectable text, live laboratory links and readable, repeating table headers.
for font,file in [('U8','DejaVuSans.ttf'),('U8B','DejaVuSans-Bold.ttf')]:pdfmetrics.registerFont(TTFont(font,'/usr/share/fonts/truetype/dejavu/'+file))
pdfmetrics.registerFontFamily('U8',normal='U8',bold='U8B',italic='U8',boldItalic='U8B')
navy=colors.HexColor('#14273b');teal=colors.HexColor('#006b83');muted=colors.HexColor('#4a6077');light=colors.HexColor('#edf3f9')
styles={
 'body':ParagraphStyle('body',fontName='U8',fontSize=10.2,leading=15.2,textColor=navy,spaceAfter=9),
 'small':ParagraphStyle('small',fontName='U8',fontSize=9.3,leading=13.5,textColor=navy,spaceAfter=5),
 'title':ParagraphStyle('title',fontName='U8B',fontSize=29,leading=35,textColor=navy,spaceAfter=20),
 'h1':ParagraphStyle('h1',fontName='U8B',fontSize=22,leading=27,textColor=navy,spaceAfter=17),
 'h2':ParagraphStyle('h2',fontName='U8B',fontSize=12.4,leading=18,textColor=teal,spaceBefore=15,spaceAfter=8,keepWithNext=True),
 'kicker':ParagraphStyle('kicker',fontName='U8B',fontSize=9,leading=14,textColor=teal,spaceAfter=10),
 'table':ParagraphStyle('table',fontName='U8',fontSize=9.4,leading=13.5,textColor=navy,spaceAfter=0),
 'th':ParagraphStyle('th',fontName='U8B',fontSize=9,leading=13,textColor=colors.white),
 'vocab':ParagraphStyle('vocab',fontName='U8',fontSize=10,leading=13.8,textColor=navy,spaceAfter=5)
}
def safe(s):return esc(str(s)).replace('−','-').replace('–','-').replace('→','-&gt;').replace('₀','0').replace('₁','1').replace('₂','2').replace('₃','3').replace('ₜ','t')
def P(s,style='body',markup=False):return Paragraph(s if markup else safe(s),styles[style])
def heading(s):return P(s,'h2')
def pdf_table(headers,rows,widths):
 t=Table([[P(x,'th') for x in headers]]+[[P(x,'table') for x in row] for row in rows],colWidths=widths,repeatRows=1,hAlign='LEFT');t.setStyle(TableStyle([('BACKGROUND',(0,0),(-1,0),navy),('ROWBACKGROUNDS',(0,1),(-1,-1),[light,colors.white]),('VALIGN',(0,0),(-1,-1),'TOP'),('TOPPADDING',(0,0),(-1,-1),8),('BOTTOMPADDING',(0,0),(-1,-1),8),('LEFTPADDING',(0,0),(-1,-1),9),('RIGHTPADDING',(0,0),(-1,-1),9),('LINEBELOW',(0,0),(-1,-1),.4,colors.HexColor('#d5e0ea'))]));t.spaceAfter=10;return t
def vocab(v):return KeepTogether([P('<b>'+safe(v['term'])+'</b> · '+safe(v['definition']),'vocab',True)])
story=[Spacer(1,40),P('UNIDAD 8 · CUADERNO DE LABORATORIOS','kicker'),P('Redes neuronales<br/>en el tiempo<br/>y en la red','title',True),P('Guía completa de ocho simulaciones para Bitcoin, Ethereum y análisis de blockchain'),Spacer(1,18),P(AUTHOR,'h2'),P('Profesor Sergio Gevatschnaider · Versión revisada · 2 de octubre de 2026'),Spacer(1,25),pdf_table(['Bloque','Preguntas centrales'],[('01-04 · Tiempo y evaluación','Ventanas, leakage, métricas, LSTM y GRU.'),('05-07 · Estructura y memoria','Grafos, centralidad, GNN y pooling recurrente.'),('08 · Explicabilidad','SHAP lineal, referencia y límites causales.')],[150,349]),Spacer(1,23),P('Datos y mecanismos reproducibles. Actividades guiadas, ejemplos comprobables, vocabulario desarrollado y enlaces a los laboratorios.'),P('<a href="'+BASE+'simuladores/" color="#006b83">Abrir los ocho laboratorios en el campus →</a>','body',True),PageBreak()]
story.extend([P('Antes de experimentar','h1'),P('Qué muestra cada recurso','h2'),P('BTC y ETH son escenarios sintéticos. La arena genera perfiles con coeficientes fijos; no entrena los algoritmos nombrados. Las GNN y las celdas usan pesos fijos. Sólo 02 ajusta una regresión ridge. Un cálculo correcto dentro de la simulación no demuestra rendimiento sobre datos reales.'),heading('Controles comunes'),pdf_table(['Control','Comportamiento'],common,[155,344]),heading('Rutina de investigación')])
story.extend(P(str(i+1)+'. '+s) for i,s in enumerate(method));story.append(PageBreak())
story.extend([P('Ruta y registro del experimento','h1'),pdf_table(['Lab','Tema','Tiempo'],[(l['id'],l['title'],str(l['minutes'])+' min') for l in labs],[40,389,70]),heading('Registro mínimo'),pdf_table(['Campo','Qué anotar'],[('Pregunta','Qué relación se explora.'),('Configuración','Semilla, escenario, horizonte y controles.'),('Resultado','Métrica o traza, unidades y JSON exportado.'),('Interpretación','Qué cambió al modificar un control.'),('Límite','Qué requeriría datos, entrenamiento o validación real.')],[140,359]),P('Sugerencia para clase: una pareja anticipa el resultado y otra intenta reconstruirlo con la traza o el registro. Contrastan sus explicaciones antes de leer la orientación de respuesta.'),PageBreak()])
for lab in labs:
 story.extend([P('LABORATORIO '+lab['id']+' · '+str(lab['minutes'])+' MINUTOS','kicker'),P(lab['title'],'h1'),P(lab['description']),P(lab['type'],'kicker'),P('<a href="'+BASE+'simuladores/'+lab['file']+'" color="#006b83">Abrir laboratorio '+lab['id']+' →</a>','body',True),heading('Controles y consecuencias'),pdf_table(['Control','Valores','Qué modifica'],lab['controls'],[108,110,281]),heading('Procedimiento')])
 story.extend(P(str(i+1)+'. '+step) for i,step in enumerate(lab['steps']));story.append(Spacer(1,8))
 story.extend([P('LABORATORIO '+lab['id']+' · RECONSTRUIR E INTERPRETAR','kicker'),heading('Un resultado que podés comprobar'),P(lab['example']),heading('Preguntas de comparación')])
 for i,a in enumerate(lab['activities']):story.append(KeepTogether([P('<b>'+str(i+1)+'. '+safe(a['prompt'])+'</b>','body',True),P('Orientación: '+a['guidance'])]))
 story.extend([Spacer(1,12),heading('Vocabulario del laboratorio '+lab['id'])]);story.extend(vocab(v) for v in lab['vocabulary']);story.append(PageBreak())
story.extend([P('APÉNDICE · CONSULTA TRANSVERSAL','kicker'),P('Vocabulario general','h1'),P('Se conservan y desarrollan todos los términos del apéndice original. Los vocabularios de cada laboratorio incorporan además contexto, fórmulas y límites de interpretación.')]);story.extend(vocab(v) for v in data['generalVocabulary']);story.append(PageBreak())
story.extend([P('Cierre y evaluación docente','h1'),P('Una actividad realizada no equivale a una respuesta correcta. Evaluá si el alumno reconstruye el cálculo, controla la comparación y reconoce el alcance del resultado.'),pdf_table(['Criterio','Evidencia observable'],closing,[165,334]),heading('Transferencia al proyecto real'),P('Documentar datos de Bitcoin o Ethereum, timestamps y disponibilidad, unidad de análisis y etiquetas; ajustar modelos en train; aplicar validación temporal y evaluar mejora incremental con ablaciones. La arena sintética y los pesos fijos preparan estas decisiones y no sustituyen ese experimento.'),PageBreak(),P('Fuentes y trazabilidad','h1')])
for url,title in refs.items():story.append(P('<a href="'+url+'" color="#006b83">'+safe(title)+'</a>','small',True))
story.extend([heading('Trazabilidad de esta revisión'),P('Basada en los ocho HTML y la guía PDF aportados por el profesor. Se corrigieron normalización GCN, concatenación GraphSAGE, atención GAT, convención GRU, conteos de bias, SHAP de referencia y métricas de la arena. Se conservaron los conceptos y los términos docentes, con explicaciones desarrolladas.')])
def footer(canvas,doc):
 canvas.saveState();w,h=A4;canvas.setStrokeColor(colors.HexColor('#cad8e6'));canvas.setLineWidth(.5);canvas.line(48,47,w-48,47);canvas.setFillColor(muted);canvas.setFont('U8',7.8);canvas.drawString(48,33,AUTHOR);canvas.drawRightString(w-48,33,str(doc.page));canvas.setFont('U8B',8);canvas.drawString(48,h-28,'U8 · REDES NEURONALES Y BLOCKCHAIN');canvas.restoreState()
doc=SimpleDocTemplate(str(ROOT/'recursos'/PDF),pagesize=A4,leftMargin=48,rightMargin=48,topMargin=58,bottomMargin=66,title='Guía completa de laboratorios · Unidad 8',author='Profesor Sergio Gevatschnaider',subject='LSTM, GRU, GNN y explicabilidad en blockchain');doc.build(story,onFirstPage=footer,onLaterPages=footer)
print('Guía HTML y PDF generadas.')
