name: Foundry CI
on:
  push:
  pull_request:

jobs:
  foundry:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: stable
        env:
          FOUNDRY_DISABLE_NIGHTLY_WARNING: 1

      - name: Instalar dependencias (si hay foundry.toml)
        if: ${{ hashFiles('foundry.toml') != '' }}
        run: forge install --no-commit

      - name: Build
        run: forge build

      - name: Test (solo si existen tests *.t.sol)
        if: ${{ hashFiles('solidity/test/**/*.t.sol', '**/test/**/*.t.sol') != '' }}
        run: forge test -vvv

      - name: Aviso si no hay tests
        if: ${{ hashFiles('solidity/test/**/*.t.sol', '**/test/**/*.t.sol') == '' }}
        run: echo "No hay tests *.t.sol; se omite forge test."
