name: Python CI
on:
  push:
  pull_request:

jobs:
  python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Instalar deps (si hay requirements.txt)
        if: ${{ hashFiles('requirements.txt') != '' }}
        run: pip install -r requirements.txt

      - name: Tests con pytest (solo si hay)
        if: ${{ hashFiles('tests/**/*.py', 'python/tests/**/*.py', 'pytest.ini', 'pyproject.toml', 'setup.cfg') != '' }}
        run: |
          pip install pytest
          pytest -q

      - name: Aviso si no hay tests de Python
        if: ${{ hashFiles('tests/**/*.py', 'python/tests/**/*.py', 'pytest.ini', 'pyproject.toml', 'setup.cfg') == '' }}
        run: echo "No hay tests de Python; se omite pytest."
