name: Markdown Links
on:
  push:
  pull_request:

jobs:
  link-checker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0   # necesario si comparamos con base-branch

      - name: markdown-link-check
        uses: gaurav-nelson/github-action-markdown-link-check@v1
        with:
          use-verbose-mode: true
          # Si no querés comparar solo cambios, poné "check-modified-files-only: false"
          check-modified-files-only: true
          base-branch: main          # <-- tu rama por defecto
          folder-path: .
          file-extension: .md
          max-depth: -1
          config-file: .github/mlc_config.json
