name: Slides (Marp)

on:
  push:
    branches: [ main ]
    paths:
      - 'slides/**/*.md'
      - 'slides/**/*.png'
      - 'slides/**/*.jpg'
      - 'slides/**/*.jpeg'
      - 'slides/**/*.svg'
      - 'slides/**/*.css'
      - '.github/workflows/slides.yml'
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: slides-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build HTML + PDF
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Marp CLI
        run: npm i -g @marp-team/marp-cli@latest

      - name: Build slides (HTML + PDF)
        run: |
          mkdir -p dist
          # HTML
          marp slides/**/*.md --html --allow-local-files -o dist/
          # PDF
          marp slides/**/*.md --pdf  --allow-local-files -o dist/
          echo "Generados:"
          ls -la dist

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: slides-dist
          path: dist
          if-no-files-found: error

  # --------- OPCIONAL: publicar en GitHub Pages ---------
  deploy:
    name: Deploy to GitHub Pages
    needs: build
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deploy.outputs.page_url }}
    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: slides-dist
          path: dist
      - name: Upload pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist
      - name: Deploy
        id: deploy
        uses: actions/deploy-pages@v4
