name: Slides (Marp)

on:
  push:
    branches: [ main ]
    paths:
      - 'slides/**/*.md'
      - '.github/workflows/slides.yml'
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: slides-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build HTML + PDF
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Acción correcta y mantenida
      - name: Convert Markdown into HTML and PDF
        uses: KoharaKazuya/marp-cli-action@v4
        # Por defecto compila todos los .md del repo.
        # Si querés limitar a /slides, podés usar un script post-step para mover/filtrar.

      - name: List outputs
        run: |
          echo "Artefactos generados:"
          ls -la .
          mkdir -p dist
          # Mover resultados a dist si querés empaquetar prolijo
          find . -maxdepth 1 -type f \( -name '*.html' -o -name '*.pdf' \) -exec mv {} dist/ \;

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: slides-dist
          path: dist
          if-no-files-found: error

  # Opcional: publicar en GitHub Pages
  deploy:
    needs: build
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deploy.outputs.page_url }}
    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: slides-dist
          path: dist
      - name: Upload pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist
      - name: Deploy to GitHub Pages
        id: deploy
        uses: actions/deploy-pages@v4
