name: Slides (Marp)

on:
  push:
    branches: [ main ]
    paths:
      - 'slides/**/*.md'
      - '.github/workflows/slides.yml'
  workflow_dispatch:

# Solo lo necesario; si vas a publicar a Pages, habilitamos pages/id-token en el job deploy.
permissions:
  contents: read

concurrency:
  group: slides-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build HTML + PDF
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Compila TODO lo que haya en slides/**/*.md a HTML y PDF dentro de dist/
      - name: Marp build
        uses: marp-team/marp-cli-action@v3
        with:
          glob: slides/**/*.md
          output: dist
          allow-local-files: true
          # Si tenés un marp.config.js en /slides, lo toma solo. Si no, no hace falta.

      - name: Subir artefacto (HTML/PDF)
        uses: actions/upload-artifact@v4
        with:
          name: slides-dist
          path: dist
          if-no-files-found: error

  # --- OPCIONAL: publicar en GitHub Pages ---
  deploy:
    needs: build
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deploy.outputs.page_url }}
    steps:
      - name: Bajar artefacto
        uses: actions/download-artifact@v4
        with:
          name: slides-dist
          path: dist
      - name: Subir artifact para Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist
      - name: Deploy a Pages
        id: deploy
        uses: actions/deploy-pages@v4

